# Generated by Django 4.0.3 on 2022-04-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_stock_num_of_units_alter_stock_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='num_of_units',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
    ]
